name: hk_kcare_linuxbuild

on:
  workflow_dispatch:
  
env:
  NODE_VERSION: '14.x'
  CI: false
  
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './projects/hk_kcare'
        
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ env.NODE_VERSION}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION}}
        cache: 'npm'
        cache-dependency-path: './projects/hk_kcare/package-lock.json'
        
    - name: Install node modules
      run: npm ci --verbose
      
    - run: npm run make-linux
    
    - name: Create ankiaddon
      run: zip -r -q '/home/runner/work/EverythingUnderTheSun/EverythingUnderTheSun/projects/hk_kcare/hk_kcare-linux-x64.zip' '/home/runner/work/EverythingUnderTheSun/EverythingUnderTheSun/projects/hk_kcare/out/hk_kcare-linux-x64'
        
    #- name: Commit and push
    #  uses: EndBug/add-and-commit@v7
    #  with:
    #    add: '["D:/a/EverythingUnderTheSun/EverythingUnderTheSun/projects/hk_kcare/hk_kcare.zip"]'
    #    message: 'Manual build for Run ${{ github.run_id }}'
    #    push: true
        
    - uses: actions/upload-artifact@v3
      with:
        name: hk_kcare_management_linux
        path: '/home/runner/work/EverythingUnderTheSun/EverythingUnderTheSun/projects/hk_kcare/hk_kcare-linux-x64.zip'
