name: hk_kcare_winbuild

on:
  workflow_dispatch:
  
env:
  NODE_VERSION: '14.x'
  CI: false
  
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: './projects/hk_kcare'
        
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ env.NODE_VERSION}}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION}}
        cache: 'npm'
        cache-dependency-path: './projects/hk_kcare/package-lock.json'
        
    - name: Install node modules
      run: npm ci --verbose
      
    - run: npm run make-win32
    
    - run: Compress-Archive -Path 'D:/a/EverythingUnderTheSun/EverythingUnderTheSun/projects/hk_kcare/out/hk_kcare-win32-x64/*' -Destination 'D:/a/EverythingUnderTheSun/EverythingUnderTheSun/projects/hk_kcare/hk_kcare_win32-x64.zip'
   
    #- name: Commit and push
    #  uses: EndBug/add-and-commit@v7
    #  with:
    #    add: '["D:/a/EverythingUnderTheSun/EverythingUnderTheSun/projects/hk_kcare/hk_kcare.zip"]'
    #    message: 'Manual build for Run ${{ github.run_id }}'
    #    push: true
        
    - uses: actions/upload-artifact@v3
      with:
        name: hk_kcare_win32-x64
        path: 'D:/a/EverythingUnderTheSun/EverythingUnderTheSun/projects/hk_kcare/out/hk_kcare-win32-x64/*'
